### ISSUE TITLE
iOS project ？

### ISSUE THREAD

**Issue by wwwang89** [chouheiwa/bitshares_wallet#1]
hi，friend，as an iOS developer,did u have some iOS bitshares_wallet projects to learn？3Q

**Comment by chouheiwa** [comment]
There is no Object-c framework for bitshares_wallet.But bitshares cli can use for it,you can use it

**Comment by chouheiwa** [comment]
Hey friend! Now I maked a framework for bitshares iOS project.
[BitsharesForiOS](https://github.com/chouheiwa/BitsharesWalletForiOS.git)
It is the demo version,so I can't push it cocoaPods.When I finished it,you can also used this framework in cocoaPods
