### ISSUE TITLE
Security flaw

### ISSUE THREAD

**Issue by abitmore** [chouheiwa/bitshares_wallet#2]
Please check

**Comment by abitmore** [comment]
Please check https://github.com/bituniverse/bitshares_wallet/issues/8 for more info.

Specifically, this code is unsafe: https://github.com/chouheiwa/bitshares_wallet/blob/7c37e866f0f797a82404dd8a60c51cb6beb208da/src/main/java/com/github/chouheiwa/wallet/socket/private_key.java#L114-L137

**Comment by chouheiwa** [comment]
Already changed
